<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>SistemaTicketsInteligente.Entidades.ComponenteDTO</RootNamespace>
    <AssemblyName>SistemaTicketsInteligente.Entidades.ComponenteDTO</AssemblyName>
  </PropertyGroup>
</Project>
